mysql_server = "root"
mysql_password = "123456"
mysql_net = "tcp"
mysql_db_name = "betting"
mysql_addr = "10.211.55.18:3306"
csv_name_list = "timi_users.csv"
initial_money = 5000
daily_reward_money = 50
enable_white_list = false
domain_name = "http://z1.zhengyinyong.com:9614"